### PR TITLE
update info for Netdata

### PR DESCRIPTION
**Pull request by andrewm4894**
Hello - i work for Netdata on data and ML (so trying to make use of the telemetry data to help make the product better or catch issues earlier - so vested interest obviously :) ),

We have, a while back, removed Google Analytics and Google Tag Manager from the agent dashboard and moved all telemetry over to a self hosted PostHog in our infra instead. So similar anon telemetry still being collected but just nothing going to Google with was one thing our users did not like, even those that did not quite mind idea of telemetry data but just hated idea of Google being part of it in any way.

Anyway - i just wanted to make the small update here to reflect the latest updates in our docs at the same link you have here.

Please let me know if anywhere else i should add to this PR to update or if this looks ok.

Cheers,
Andy

Please refer to contributing documentation for any questions: [CONTRIBUTING](/docs/CONTRIBUTING.md)

### Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] I've run `.\build.ps1` and all tests are green

### CODE REVIEW

**Comment by andrewm4894** [comment]
I'm a little unsure how to add the two other ways to opt out to the `netdata.json` file. 

Main thing i wanted to update was the text really anyway to update the move from GA/GTM to PostHog. 

I had them like below:

```
##### 2. Create empty file

Create an empty file in your Netdata configuration directory to opt out.

###### Scope: 👤 User

| OS      | Path                                                      |
|---------|-----------------------------------------------------------|
| Linux   | `/etc/netdata/.opt-out-from-anonymous-statistics`         |

##### 3. Add option during installer script

Pass the option `--disable-telemetry` to the installer script when installing or upgrading.

```

**Comment by andrewm4894** [comment]
feel free to also just make this update yourself if easier too and not to much hassle. 

cheers!

**Comment by beatcracker** [comment]
> I'm a little unsure how to add the two other ways to opt out to the netdata.json file.

You can add them as [noop](https://github.com/beatcracker/toptout/blob/master/data/README.md#no-operation) targets, example: [buildbuddy.json#L19-L25](https://github.com/beatcracker/toptout/blob/5dac7cf90b58d7c7a0fe018c663946db38efc5bb/data/buildbuddy.json#L19-L25). They will be rendered in README like this: https://github.com/beatcracker/toptout#1-visit-links-for-more-details-4

And then comes the tricky part, where you need to run `build.ps1` to generate all the stuff and commit it. It looks like you've allowed changes from maintainers (it's surprisingly [tricky to figure out](https://stackoverflow.com/a/60064666/4424236)!), so I could doo this for you and update PR accordingly.

**Comment by andrewm4894** [comment]
If you could do it if it's not too much hassle that would be great.

I'll probably mess up and take another few back and forths so it might be
easier if you can.

I'm a data guy who just about knows python and sql lol :)

**Comment by beatcracker** [comment]
Sure, I'll handle this, thanks!

**Comment by andrewm4894** [comment]
Thank you!

**Pull request merged**
